[project]
name = "database-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "streamlit>=1.46.0",
    "tabulate>=0.9.0",
    "watchdog>=6.0.0",
]
